import { Article } from './definitions';

export const latestArticles: Article[] = [
  {
    id: '1',
    slug: 'uvira-falls-m23-advance',
    title: 'Crisis in the East: Uvira Falls as M23 Advances South',
    excerpt: 'The strategic city of Uvira has reportedly fallen, cutting off key supply routes to Bujumbura. Humanitarian agencies warn of a massive displacement crisis as fighting intensifies.',
    coverImage: '/images/uvira-tombe.jpeg',
    imageCaption: 'M23 convoy entering Uvira, December 2025.',
    imageCredit: 'Photo by AFP/Getty Images',
    category: 'politics',
    author: { name: 'Twirwaneho Live' },
    publishedAt: '2025-12-16T06:00:00Z',
  },
  {
    id: '2',
    slug: 'minembwe-blockade-humanitarian',
    title: 'Minembwe Under Siege: The Silent Blockade of the Highlands',
    excerpt: 'Cut off from the world, the Banyamulenge community in Minembwe faces critical shortages of medicine and food. Local leaders accuse regional forces of enforcing a "starvation strategy."',
    coverImage: '/images/mikenke-hit.jpeg',
    imageCaption: 'Mikenke village hit by bombardment, December 2025.',
    imageCredit: 'Community Archive',
    category: 'human-rights',
    author: { name: 'iMulenge Iwacu' },
    publishedAt: '2025-12-15T14:30:00Z',
  },
  {
    id: '3',
    slug: 'twirwaneho-statement-defense',
    title: 'Inside the Twirwaneho: "We Are Fighting for Survival, Not Power"',
    excerpt: 'Exclusive: A commander from the self-defense group speaks out on the recent clashes in the Hauts-Plateaux, denying alliance claims and insisting their mission is purely to protect cattle and kin.',
    coverImage: '/images/twiraneho-triumph.jpeg',
    imageCaption: 'A Twirwaneho fighter overlooking the Itombwe highlands after a successful operation.',
    imageCredit: 'Exclusive',
    category: 'exclusive',
    author: { name: 'Twirwaneho Media' },
    publishedAt: '2025-12-14T09:15:00Z',
  },
  {
    id: '4',
    slug: 'luanda-summit-peace-talks',
    title: 'Luanda Summit Stalls: No Agreement on East DRC Ceasefire',
    excerpt: 'Regional heads of state failed to reach a consensus in Angola yesterday, as accusations of cross-border support for armed groups derailed the peace process once again.',
    coverImage: 'https://images.unsplash.com/photo-1575320181282-9afab399332c?auto=format&fit=crop&q=80&w=800',
    imageCaption: 'Delegates gather in Luanda for high-stakes peace talks.',
    imageCredit: 'AFP',
    category: 'diplomacy',
    author: { name: 'Regional Desk' },
    publishedAt: '2025-12-13T18:45:00Z',
  },
];